### ISSUE TITLE
Comparision to Vector (https://vector.dev/)

### ISSUE THREAD

**Issue by ypid-geberit** [jedisct1/flowgger#59]
Seems you have similarities with https://vector.dev/. Both are written in Rust. Do you know this project?

**Comment by vche** [comment]
Hi !
Yes, I looked at it a year ago, while it still was in beta. 
I did not test it though and am unable to provide you any comparison or benchmarking.

**Comment by ypid-geberit** [comment]
At least for my use case, Vector seems better suited because Flowgger is currently missing ES output (ref: https://github.com/awslabs/flowgger/issues/11).

@vche Why do you prefer Flowgger over Vector?

**Comment by vche** [comment]
You are right that vector has more output modules, and if you need ES in flowgger it would need to be added, which is not currently planned.

Flowgger is smaller than vector and has a less code. It allows compiling only the required input/output in order to minimize space and memory footprint (although to be fair i don't know if vector allows that as well now), as well as required dependencies. 

Using a recently added passthrough options allows getting data from different sources, e.g. using different versions of RFC3164 for instance, or add a custom timestamp to the output file, features that we need.

In addition, at the time we started to work with flowgger, vector was only in alpha while flowgger was in use for much longer with a better history record regarding stability. 

Keep in mind that I only looked at vector a year ago when it was still in alpha, so a lot might have changed since then.

**Comment by ypid-geberit** [comment]
Thank you very much.

**Comment by Hoverbear** [comment]
There is also the http://tremor.rs/ project in our cozy ecosystem ☺️ !

Hi @Licenser!
